/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.morgue.api.dao.hibernate;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.openmrs.Location;
import org.openmrs.Patient;
import org.openmrs.api.db.DAOException;
import org.openmrs.module.morgue.MorgueCompartment;
import org.openmrs.module.morgue.MorgueStorageAssignment;
import org.openmrs.module.morgue.api.dao.MorgueStorageAssignmentDao;

/**
 * JDBC backed implementation of {@link MorgueStorageAssignmentDao}.
 * <p>
 * {@link MorgueStorageAssignment} is intentionally not a Hibernate entity - see
 * {@link MorgueJdbcSupport} for why - so every statement here is hand written SQL run through
 * {@code doWork} / {@code doReturningWork} on the current Hibernate session, keeping the work on
 * the same connection and transaction as the rest of the request.
 * <p>
 * The compartment and its storage unit used to be Hibernate many-to-ones; they are now fetched in
 * the same statement by joining {@code morgue_compartment} and {@code morgue_storage_unit}, and the
 * patient is loaded off the session once the result set has been closed.
 * <p>
 * Note that {@code morgue_storage_assignment} has no {@code uuid} column, and the Hibernate mapping
 * that this class replaces did not map one either. An assignment's uuid therefore remains the value
 * generated by {@code BaseOpenmrsObject} in memory and is not persisted or looked up, exactly as
 * before.
 */
public class HibernateMorgueStorageAssignmentDao implements MorgueStorageAssignmentDao {
	
	static final String TABLE = "morgue_storage_assignment";
	
	static final String ALIAS = "a";
	
	static final String PREFIX = "a_";
	
	private static final String[] OWN_COLUMNS = { "storage_assignment_id", "compartment_id", "patient_id", "date_admitted",
	        "date_discharged", "status" };
	
	private SessionFactory sessionFactory;
	
	public void setSessionFactory(SessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}
	
	/**
	 * @see MorgueStorageAssignmentDao#getActiveAssignmentForPatient(Patient)
	 */
	@Override
	public MorgueStorageAssignment getActiveAssignmentForPatient(Patient patient) {
		if (patient == null || patient.getPatientId() == null) {
			return null;
		}
		
		final String sql = baseSelect() + " where " + ALIAS + ".patient_id = ? and " + ALIAS
		        + ".date_discharged is null and " + ALIAS + ".voided = false";
		final Integer patientId = patient.getPatientId();
		
		Session session = sessionFactory.getCurrentSession();
		List<Row> rows = session.doReturningWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql)) {
				ps.setInt(1, patientId);
				return readRows(ps);
			}
		});
		
		if (rows.isEmpty()) {
			return null;
		}
		if (rows.size() > 1) {
			throw new DAOException("Patient " + patientId + " has more than one active morgue storage assignment");
		}
		return resolve(session, rows.get(0));
	}
	
	/**
	 * @see MorgueStorageAssignmentDao#getAssignmentsForPatient(Patient)
	 */
	@Override
	public List<MorgueStorageAssignment> getAssignmentsForPatient(Patient patient) {
		if (patient == null || patient.getPatientId() == null) {
			return new ArrayList<>();
		}
		
		final String sql = baseSelect() + " where " + ALIAS + ".patient_id = ? and " + ALIAS
		        + ".voided = false order by " + ALIAS + ".storage_assignment_id";
		final Integer patientId = patient.getPatientId();
		
		Session session = sessionFactory.getCurrentSession();
		List<Row> rows = session.doReturningWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql)) {
				ps.setInt(1, patientId);
				return readRows(ps);
			}
		});
		
		return resolveAll(session, rows);
	}
	
	/**
	 * @see MorgueStorageAssignmentDao#getAssignmentsForLocation(Location, Boolean, Date, Date,
	 *      Date)
	 */
	@Override
	public List<MorgueStorageAssignment> getAssignmentsForLocation(Location location, Boolean includeVoided,
	        Date createdOnOrAfter, Date admittedOnOrAfter, Date admittedOnOrBefore) {
		StringBuilder sql = new StringBuilder(baseSelect());
		List<String> clauses = new ArrayList<>();
		List<Object> parameters = new ArrayList<>();
		
		if (location != null) {
			clauses.add(HibernateMorgueStorageUnitDao.ALIAS + ".location_id = ?");
			parameters.add(location.getLocationId());
		}
		if (includeVoided == null || !includeVoided) {
			clauses.add(ALIAS + ".voided = false");
		}
		if (createdOnOrAfter != null) {
			clauses.add(ALIAS + ".date_created >= ?");
			parameters.add(createdOnOrAfter);
		}
		if (admittedOnOrAfter != null) {
			clauses.add(ALIAS + ".date_admitted >= ?");
			parameters.add(admittedOnOrAfter);
		}
		if (admittedOnOrBefore != null) {
			clauses.add(ALIAS + ".date_admitted <= ?");
			parameters.add(admittedOnOrBefore);
		}
		if (!clauses.isEmpty()) {
			sql.append(" where ").append(String.join(" and ", clauses));
		}
		sql.append(" order by ").append(ALIAS).append(".storage_assignment_id");
		
		final String statement = sql.toString();
		
		Session session = sessionFactory.getCurrentSession();
		List<Row> rows = session.doReturningWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(statement)) {
				bind(ps, parameters);
				return readRows(ps);
			}
		});
		
		return resolveAll(session, rows);
	}
	
	/**
	 * @see MorgueStorageAssignmentDao#getAssignmentsForCompartment(MorgueCompartment)
	 */
	@Override
	public List<MorgueStorageAssignment> getAssignmentsForCompartment(MorgueCompartment compartment) {
		if (compartment == null || compartment.getCompartmentId() == null) {
			return new ArrayList<>();
		}
		
		final String sql = baseSelect() + " where " + ALIAS + ".compartment_id = ? and " + ALIAS
		        + ".voided = false order by " + ALIAS + ".storage_assignment_id";
		final Integer compartmentId = compartment.getCompartmentId();
		
		Session session = sessionFactory.getCurrentSession();
		List<Row> rows = session.doReturningWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql)) {
				ps.setInt(1, compartmentId);
				return readRows(ps);
			}
		});
		
		return resolveAll(session, rows);
	}
	
	/**
	 * Inserts the assignment when it has no id yet, otherwise updates the existing row. This
	 * mirrors the {@code saveOrUpdate} semantics the DAO had while the class was Hibernate mapped.
	 * 
	 * @see MorgueStorageAssignmentDao#saveAssignment(MorgueStorageAssignment)
	 */
	@Override
	public MorgueStorageAssignment saveAssignment(MorgueStorageAssignment assignment) {
		if (assignment == null) {
			throw new DAOException("Assignment is required");
		}
		
		if (assignment.getStorageAssignmentId() == null) {
			insert(assignment);
		} else {
			update(assignment);
		}
		return assignment;
	}
	
	/**
	 * @see MorgueStorageAssignmentDao#deleteAssignment(MorgueStorageAssignment)
	 */
	@Override
	public void deleteAssignment(MorgueStorageAssignment assignment) {
		if (assignment == null || assignment.getStorageAssignmentId() == null) {
			throw new DAOException("Cannot delete a morgue storage assignment that has not been saved");
		}
		
		final String sql = "delete from " + TABLE + " where storage_assignment_id = ?";
		final Integer id = assignment.getStorageAssignmentId();
		
		sessionFactory.getCurrentSession().doWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql)) {
				ps.setInt(1, id);
				ps.executeUpdate();
			}
		});
	}
	
	private void insert(MorgueStorageAssignment assignment) {
		MorgueJdbcSupport.stampForInsert(assignment);
		
		final String sql = "insert into " + TABLE + " (compartment_id, patient_id, date_admitted, date_discharged, "
		        + "status, creator, date_created, changed_by, date_changed, voided, voided_by, date_voided, "
		        + "voided_reason) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		
		Integer generatedId = sessionFactory.getCurrentSession().doReturningWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
				int i = bindOwnColumns(ps, 1, assignment);
				MorgueJdbcSupport.bindAudit(ps, i, assignment);
				ps.executeUpdate();
				return MorgueJdbcSupport.readGeneratedId(ps);
			}
		});
		
		assignment.setStorageAssignmentId(generatedId);
	}
	
	private void update(MorgueStorageAssignment assignment) {
		MorgueJdbcSupport.stampForUpdate(assignment);
		
		final String sql = "update " + TABLE + " set compartment_id = ?, patient_id = ?, date_admitted = ?, "
		        + "date_discharged = ?, status = ?, creator = ?, date_created = ?, changed_by = ?, date_changed = ?, "
		        + "voided = ?, voided_by = ?, date_voided = ?, voided_reason = ? where storage_assignment_id = ?";
		
		sessionFactory.getCurrentSession().doWork(connection -> {
			try (PreparedStatement ps = connection.prepareStatement(sql)) {
				int i = bindOwnColumns(ps, 1, assignment);
				i = MorgueJdbcSupport.bindAudit(ps, i, assignment);
				ps.setInt(i, assignment.getStorageAssignmentId());
				ps.executeUpdate();
			}
		});
	}
	
	private static int bindOwnColumns(PreparedStatement ps, int index, MorgueStorageAssignment assignment)
	        throws SQLException {
		int i = index;
		MorgueJdbcSupport.setInteger(ps, i++, compartmentId(assignment));
		MorgueJdbcSupport.setInteger(ps, i++, patientId(assignment));
		ps.setTimestamp(i++, MorgueJdbcSupport.toTimestamp(assignment.getDateAdmitted()));
		ps.setTimestamp(i++, MorgueJdbcSupport.toTimestamp(assignment.getDateDischarged()));
		ps.setString(i++, assignment.getStatus());
		return i;
	}
	
	private static void bind(PreparedStatement ps, List<Object> parameters) throws SQLException {
		for (int i = 0; i < parameters.size(); i++) {
			Object parameter = parameters.get(i);
			if (parameter instanceof Date) {
				ps.setTimestamp(i + 1, MorgueJdbcSupport.toTimestamp((Date) parameter));
			} else {
				MorgueJdbcSupport.setInteger(ps, i + 1, (Integer) parameter);
			}
		}
	}
	
	private static Integer compartmentId(MorgueStorageAssignment assignment) {
		return assignment.getCompartment() == null ? null : assignment.getCompartment().getCompartmentId();
	}
	
	private static Integer patientId(MorgueStorageAssignment assignment) {
		return assignment.getPatient() == null ? null : assignment.getPatient().getPatientId();
	}
	
	private static String baseSelect() {
		return "select " + MorgueJdbcSupport.selectList(ALIAS, PREFIX, OWN_COLUMNS, MorgueJdbcSupport.AUDIT_COLUMNS) + ", "
		        + HibernateMorgueCompartmentDao.selectList() + ", " + HibernateMorgueStorageUnitDao.selectList() + " from "
		        + TABLE + " " + ALIAS + " inner join " + HibernateMorgueCompartmentDao.TABLE + " "
		        + HibernateMorgueCompartmentDao.ALIAS + " on " + HibernateMorgueCompartmentDao.ALIAS + ".compartment_id = "
		        + ALIAS + ".compartment_id " + HibernateMorgueCompartmentDao.storageUnitJoin();
	}
	
	private static List<Row> readRows(PreparedStatement ps) throws SQLException {
		List<Row> rows = new ArrayList<>();
		try (ResultSet rs = ps.executeQuery()) {
			while (rs.next()) {
				rows.add(readRow(rs));
			}
		}
		return rows;
	}
	
	private static Row readRow(ResultSet rs) throws SQLException {
		Row row = new Row();
		row.assignment.setStorageAssignmentId(MorgueJdbcSupport.getInteger(rs, PREFIX + "storage_assignment_id"));
		row.assignment.setDateAdmitted(MorgueJdbcSupport.getDate(rs, PREFIX + "date_admitted"));
		row.assignment.setDateDischarged(MorgueJdbcSupport.getDate(rs, PREFIX + "date_discharged"));
		row.assignment.setStatus(rs.getString(PREFIX + "status"));
		row.patientId = MorgueJdbcSupport.getInteger(rs, PREFIX + "patient_id");
		row.audit = MorgueJdbcSupport.readAudit(rs, PREFIX);
		row.compartmentRow = HibernateMorgueCompartmentDao.readRow(rs);
		return row;
	}
	
	private static List<MorgueStorageAssignment> resolveAll(Session session, List<Row> rows) {
		List<MorgueStorageAssignment> assignments = new ArrayList<>(rows.size());
		for (Row row : rows) {
			assignments.add(resolve(session, row));
		}
		return assignments;
	}
	
	private static MorgueStorageAssignment resolve(Session session, Row row) {
		row.assignment.setCompartment(HibernateMorgueCompartmentDao.resolve(session, row.compartmentRow));
		if (row.patientId != null) {
			row.assignment.setPatient(session.get(Patient.class, row.patientId));
		}
		MorgueJdbcSupport.applyAudit(session, row.assignment, row.audit);
		return row.assignment;
	}
	
	/**
	 * A row read straight off the {@link ResultSet}. Foreign keys stay as ids until the result set
	 * is closed, so that resolving them never issues a nested query on the shared connection.
	 */
	private static final class Row {
		
		private final MorgueStorageAssignment assignment = new MorgueStorageAssignment();
		
		private Integer patientId;
		
		private MorgueJdbcSupport.AuditRow audit;
		
		private HibernateMorgueCompartmentDao.Row compartmentRow;
	}
}
